messages:
  prefix: "&8[&eQR&8] "
  onlyForPlayer: "&cOnly for players!"
  handNotEmpty: "&cYour hand should be empty!"
  success: "&aYou have successfully created a QR-Code!"
settings:
  changeMapName: false
  DefaultBackground: background.png
  BackgroundActive: activeback.png
  QRLogo: SNQRLogo.png
