name: PlayerQRMap
main: com.sovereigncraft.playerqrcodemap.Main
author: Sovtoshi
version: 1.0
api-version: 1.13
commands:
  qrcode:
    description: Create a QR-Code
    usage: /qrcode <text|link>
    permission: qrcodemap.create
    aliases:
      - qr
      - qc
  mapinterface:
    description: Update interface map
    usage: /playerqrcode <text|link>
    permission: playerqrcode.create
    aliases:
      - plqr
      - plqc